<?php

namespace gesGfctBundle\Repository;

/**
 * profesoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class profesoresRepository extends \Doctrine\ORM\EntityRepository
{
}
